### ISSUE TITLE
alexa with ibm discovery

### ISSUE THREAD

**Issue by Natiqah07** [fe01134/alexa-ask-watson#6]
hi!
i am having trouble calling ibm discovery. is there a way for alexa to call ibm discovery?

thank you

**Comment by fe01134** [comment]
Hi Nati.  Discovery Service in essence allows you to index documents and website and enrich the entries with additional metadata.  The service is based on Solr

**Comment by fe01134** [comment]
Hi Nati.  Discovery Service in essence allows you to index documents and website and enrich the entries with additional metadata.  The service is based on Solr
